In [1]:
#https://gist.github.com/jiahao87/50cec29725824da7ff6dd9314b53c4b3

In [2]:
!pip install ohmeow-blurr -q
!pip install datasets -q
!pip install bert-score -q
!pip install transformers

     |████████████████████████████████| 91 kB 3.4 MB/s
     |████████████████████████████████| 189 kB 26.5 MB/s
     |████████████████████████████████| 3.8 MB 41.4 MB/s
     |████████████████████████████████| 312 kB 51.0 MB/s
     |████████████████████████████████| 43 kB 2.1 MB/s
     |████████████████████████████████| 1.2 MB 42.1 MB/s
     |████████████████████████████████| 55 kB 3.9 MB/s
     |████████████████████████████████| 895 kB 46.3 MB/s
     |████████████████████████████████| 596 kB 35.6 MB/s
     |████████████████████████████████| 6.5 MB 35.8 MB/s
     |████████████████████████████████| 67 kB 4.8 MB/s
     |████████████████████████████████| 212 kB 48.3 MB/s
     |████████████████████████████████| 134 kB 49.6 MB/s
     |████████████████████████████████| 1.1 MB 35.7 MB/s
     |████████████████████████████████| 127 kB 48.1 MB/s
     |████████████████████████████████| 271 kB 46.7 MB/s
     |████████████████████████████████| 144 kB 53.0 MB/s
     |████████████████████████████████| 94 kB 3.7 MB/s
  Building wheel for seqeval (setup.py) ... done
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
datascience 0.10.6 requires folium==0.2.1, but you have folium 0.8.3 which is incompatible.
     |████████████████████████████████| 60 kB 2.8 MB/s
Requirement already satisfied: transformers in /usr/local/lib/python3.7/dist-packages (4.17.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.7/dist-packages (from transformers) (1.21.5)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.7/dist-packages (from transformers) (21.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.7/dist-packages (from transformers) (2019.12.20)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from transformers) (2.23.0)
Requirement already satisfied: sacremoses in /usr/local/lib/python3.7/dist-packages (from transformers) (0.0.47)
Requirement already satisfied: huggingface-hub<1.0,>=0.1.0 in /usr/local/lib/python3.7/dist-packages (from transformers) (0.4.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.7/dist-packages (from transformers) (4.63.0)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.7/dist-packages (from transformers) (4.11.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.7/dist-packages (from transformers) (6.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.7/dist-packages (from transformers) (3.6.0)
Requirement already satisfied: tokenizers!=0.11.3,>=0.11.1 in /usr/local/lib/python3.7/dist-packages (from transformers) (0.11.6)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.7/dist-packages (from huggingface-hub<1.0,>=0.1.0->transformers) (3.10.0.2)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from packaging>=20.0->transformers) (3.0.7)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata->transformers) (3.7.0)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->transformers) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->transformers) (2021.10.8)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->transformers) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->transformers) (1.25.11)
Requirement already satisfied: click in /usr/local/lib/python3.7/dist-packages (from sacremoses->transformers) (7.1.2)
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from sacremoses->transformers) (1.15.0)
Requirement already satisfied: joblib in /usr/local/lib/python3.7/dist-packages (from sacremoses->transformers) (1.1.0)

In [3]:
import datasets
import pandas as pd
from fastai.text.all import *
from transformers import *

from blurr.data.all import *
from blurr.modeling.all import *

In [4]:
df_news = pd.read_csv('news_summary - train.csv', 
                       engine='python',
                       encoding='unicode_escape')

In [5]:
df_news = df_news[['Text', 'Summary']]
df_news.head()

,Text,Summary
0,"Motorman Mahendra Prasad called up the railway police control room on Sunday and informed officials that a 15-year-old boy and 25-year-old youth had fallen from a train and were found injured on the tracks between Lower Parel and Elphinston stations. Mohammed Ansari, 25, and Mohammed Nisar, 15, were among the 10 people injured while travelling on Western and Central Railway line on Sunday.Sunday recorded 13 track deaths, the highest on a single day this year. In the past six months, around 1,590 people have been killed while travelling on trains ? 676 died after falling off trains. On an a...","As many as 13 people died while travelling in Mumbai's local trains on Sunday, according to railway data. Almost 1,600 people have been killed while travelling in trains in the past six months, it added. Of the 1,600, 700 lost their lives by falling off the train,147 were killed while crossing railway tracks, and 20 people died of electric shock."
1,"Bored in confines of a sprawling resort in Bengaluru, the Congress flock of 44 MLAs is a frustrated lot now. Following strict orders of the Karnataka Power Minister DK Shivakumar, the MLAs are not allowed to venture out in the city. While the minister is presently in New Delhi to seek further course of action, 30 MLAs have been put in-charge of the discipline. But few defiant MLAs did head out in the city for sightseeing, shopping, to visit temples, much to the dismay of those still under curbs. The MLAs who were allowed to go out are supposedly those, the Congress is confident of not ditc...","The Gujarat Congress MLAs staying in a Bengaluru resort are not allowed to go out, and 30 MLAs from Karnataka have been put in charge of the discipline. The party has planned seminars and programmes for their entertainment inside the resort. These include a lecture on the corruption charges against UPA, and Congress' achievements in 60 years, transparency and accountability."
2,"There is only a 5% chance that the Earth will avoid warming by at least 2C come the end of the century, according to new research that paints a sobering picture of the international effort to stem dangerous climate change.Global trends in the economy, emissions and population growth make it extremely unlikely that the planet will remain below the 2C threshold set out in the Paris climate agreement in 2015, the study states. The Paris accord, signed by 195 countries, commits to holding the average global temperature to ?well below 2C? above pre-industrial levels and sets a more aspirational...","According to a recently published US-based research, there is only a 5% chance that Earth will avoid warming by at least 2°C by 2100, the threshold set in the Paris climate agreement. The research studied global trends in the economy, emissions and population growth, and further stated that there is 1% chance that temperatures will rise by less than 1.5°C."
3,"After a swarm of bees held up a Hyderabad-Pune flight last week for more than one hour, the country aviation regulator said it will investigate how a bee hive was allowed to flourish in the airport area. The flight on July 26 was held up when the ATR?72 - a short-haul aircraft - was besieged by bees. The flight, which was scheduled to take off at around 6.25pm, took off only at around 7.22pm after a repellent spray was used to clear the insects from the apron area. This was the first such incident in the past five years. A Directorate General of Civil Aviation (DGCA) official on Monday sa...","A swarm of bees reportedly attacked a Hyderabad-Pune flight last week and delayed it by almost an hour. The flight was able to take off only after a repellent spray was used to clear the insects from the area. ""We will look into the matter and necessary action will be taken,"" a Directorate General of Civil Aviation official said."
4,"New Delhi, Aug 1 (PTI) Flight Lt Shikha Pandey, a member of the Indian womens cricket team, was today felicitated by Indian Air Force chief BS Dhanoa for her sterling performance at the recent World Cup. Pandey was awarded the chief of the air staff commendation by Air Chief Marshal Dhanoa for her performance at the recently concluded ICC Women World Cup, the IAF said. The Indian womens cricket team finished runner-up, losing to England narrowly by nine runs. However, the teams magnificent performance to reach the finals won laurels from all quarters.","Flight Lt Shikha Pandey, a member of the Indian women's cricket team, was felicitated by Indian Air Force Chief BS Dhanoa for her performance at the Women's World Cup 2017. Pandey, commissioned in the IAF on June 30, 2012, as an air traffic control officer, was awarded the Chief of the Air Staff commendation by the Air Chief Marshal."

In [6]:
df_news = df_news.sample(15)

In [7]:
df_news.shape

(15, 2)

In [8]:
df_news = df_news.dropna()

In [9]:
for col in df_news.columns.tolist():
    df_news[col+"_num_words"] = df_news[col].apply(lambda x: len(x.split()))
df_news.head()

,Text,Summary,Text_num_words,Summary_num_words
52,"Hollywood actor Ryan Reynolds seems to know exactly what Deadpool fans want to see. The 40-year-old actor took to Twitter and shared the first image of actress Zazie Beetz as Domino.With his usual quirky style, he captioned the snap, ?Some people just know how to work a red carpet.? In the photo, Domino is seen lounging in front of a fireplace atop of Deadpool, who has been flattened out into a rug.Some people just know how to work a red carpet. #Domino #DeadPool2 pic.twitter.com/llCc8JfKT6? Ryan Reynolds (@VancityReynolds) July 31, 2017The snap is a callback to one of the first photos of ...","Hollywood actor Ryan Reynolds took to social media to share the first look of actress Zazie Beetz from the upcoming superhero film 'Deadpool 2'. ""Some people just know how to work a red carpet,"" wrote Ryan. Zazie will portray the superhero character 'Domino' in the film. Directed by David Leitch, 'Deadpool 2' is scheduled to release on June 1, 2018.",246,60
82,"The Chhattisgarh government will begin an ambulance service for cows, chief minister Raman Singh said, joining a number of BJP-ruled states to put a stronger focus on protection of the animal that is considered sacred by Hindus.The service will be started in ten districts in the next few months, Singh said, addressing a programme organised by the state?s commission for protection of cows at Pandit Ravi Shankar University on Sunday.Protecting cows and promoting products derived from them has been in focus since the rise of the Bharatiya Janata Party with the election of Prime Minister Nare...","Chhattisgarh Chief Minister Raman Singh on Sunday announced that ambulance service for cows will be started in 10 districts of the state over the next few months. He also urged people to support organic farming and biogas in order to promote a cow-based economy. Earlier this year, Singh had said that anyone found killing cows in Chhattisgarh will be hanged.",253,60
110,"The state environment department is drawing up a plan to properly dispose of tonnes of road dust that is collected by mechanical sweepers every day.The city has more than a dozen mechanical sweepers which keeps the road free of dust. More such vehicles are being procured by both the civic bodies and the PWD.?There is, however, no proper mechanism or standard operating procedure on how to dump the dust collected so that they don?t return to the city after disposal,? said a senior official of the state public works department.Road dust is one of the major contributors to the particulate poll...","Delhi's Department of Environment is reportedly drawing a standard operating procedure to dispose the road dust collected by more than a dozen mechanical sweepers in order to control the air pollution level in the city. Additionally, the Public Works Department has floated a tender to procure six more sweeping machines this year.",430,52
140,"New Delhi, Jul 30 (PTI) Post-GST, travel time for long- haul trucks have reduced by at least a fifth, Ministry of Road Transport and Highways has said. ""A typical truck spent 20 per cent of its runtime at interstate checkposts (pre GST)...Inter-state check posts removed, travel time of long-haul trucks, other cargo vehicles cut by at least one-fifth,"" the Ministry has said in a recent report. On an average, a truck in India runs an annual distance of 60,000 kms, as against 200,000 km in the West. The Ministry said trucks earlier took 50-65 hours in reaching Kolkata from Chennai and the tra...","The travel time for long-haul trucks has reduced by at least a fifth after GST was introduced, Road Transport and Highways Ministry has said. Trucks earlier took 50-65 hours to reach Kolkata from Chennai and it now stands reduced by 20%, it reported. The collection of sales tax at inter-state check posts had led to major traffic congestion, it added.",414,60
34,"Vishal Rana (21) and Hari Om (26), accused in the 2015 lynching of Mohammad Ikhlaq in Bisada for allegedly slaughtering a cow, was granted bail by the Allahabad high court on Monday.Vishal?s father Sanjay Rana (47), a local BJP leader, said his son ?got justice? because Uttar Pradesh ?has a BJP government?.?Though government has no say in court?s decision, it ensured justice is done,? he said, and claimed that in the previous regime, officials were did not ensure fair investigation.Sanjay also claimed that ?the whole village, including Muslims, were happy over the bail of my son?.?I do not...","The Allahabad High Court on Monday granted bail to two accused in the 2015 lynching of Mohammad Akhlaq in Dadri for allegedly slaughtering a cow. A local BJP leader, who is the father of one of the accused who got bail, praised the BJP for providing justice to his son. Notably, 14 people have been granted bail in the case.",359,60

In [10]:
df_news.describe()

       Text_num_words  Summary_num_words
count       15.000000          15.000000
mean       506.400000          58.400000
std        619.815157           2.529822
min         67.000000          52.000000
25%        248.000000          57.500000
50%        287.000000          60.000000
75%        422.000000          60.000000
max       2014.000000          60.000000

In [11]:
# df = df_news.sample(100)

In [12]:
# from datasets import Dataset

# dataset = Dataset.from_pandas(df)

In [13]:
# dataset

In [14]:
pretrained_model_name = "google/pegasus-xsum"
hf_arch, hf_config, hf_tokenizer, hf_model = BLURR.get_hf_objects(pretrained_model_name, 
                                                                  model_cls=AutoModelForSeq2SeqLM)

hf_arch, type(hf_config), type(hf_tokenizer), type(hf_model)

Downloading:   0%|          | 0.00/1.36k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/87.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.82M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/3.36M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/65.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/2.12G [00:00<?, ?B/s]

('pegasus',
 transformers.models.pegasus.configuration_pegasus.PegasusConfig,
 transformers.models.pegasus.tokenization_pegasus_fast.PegasusTokenizerFast,
 transformers.models.pegasus.modeling_pegasus.PegasusForConditionalGeneration)

In [15]:
text_gen_kwargs = default_text_gen_kwargs(hf_config,
                                          hf_model,
                                          task='summarization')
text_gen_kwargs

{'bad_words_ids': None,
 'bos_token_id': 0,
 'decoder_start_token_id': 0,
 'diversity_penalty': 0.0,
 'do_sample': False,
 'early_stopping': False,
 'encoder_no_repeat_ngram_size': 0,
 'eos_token_id': 1,
 'forced_bos_token_id': None,
 'forced_eos_token_id': 1,
 'length_penalty': 0.6,
 'max_length': 64,
 'min_length': 0,
 'no_repeat_ngram_size': 0,
 'num_beam_groups': 1,
 'num_beams': 8,
 'num_return_sequences': 1,
 'output_attentions': False,
 'output_hidden_states': False,
 'output_scores': False,
 'pad_token_id': 0,
 'remove_invalid_values': False,
 'repetition_penalty': 1.0,
 'return_dict_in_generate': False,
 'temperature': 1.0,
 'top_k': 50,
 'top_p': 1.0,
 'typical_p': 1.0,
 'use_cache': True}

In [16]:
hf_batch_tfm = HF_Seq2SeqBeforeBatchTransform(hf_arch, hf_config,
                                              hf_tokenizer,
                                              hf_model, 
                                              max_length=100, 
                                              max_tgt_length=30, 
                                              text_gen_kwargs=text_gen_kwargs)

In [17]:
blocks = (HF_Seq2SeqBlock(before_batch_tfm=hf_batch_tfm), noop)

In [18]:
dblock = DataBlock(blocks=blocks,
                   get_x=ColReader('Text'),
                   get_y=ColReader('Summary'),
                   splitter=RandomSplitter())

In [19]:
batch_size=2
dls = dblock.dataloaders(df_news, bs=batch_size)

In [20]:
len(dls.train.items), len(dls.valid.items)

(12, 3)

In [21]:
b = dls.one_batch()
len(b), b[0]['input_ids'].shape, b[1].shape

(2, torch.Size([2, 100]), torch.Size([2, 73]))

In [22]:
dls.show_batch(dataloaders=dls, max_n=2)

## Training

In [23]:
seq2seq_metrics = {
        'rouge': {
            'compute_kwargs': { 'rouge_types': ["rouge1", "rouge2", "rougeL"], 'use_stemmer': True },
            'returns': ["rouge1", "rouge2", "rougeL"]
        },
        'bertscore': {
            'compute_kwargs': { 'lang': 'en' },
            'returns': ["precision", "recall", "f1"]
        },
        'bleu': { 'returns': "bleu" },
    }

In [24]:
model = HF_BaseModelWrapper(hf_model)
learn_cbs = [HF_BaseModelCallback]
fit_cbs = [HF_Seq2SeqMetricsCallback(custom_metrics=seq2seq_metrics)]

learn = Learner(dls, 
                model,
                opt_func=ranger,
                loss_func=CrossEntropyLossFlat(),
                cbs=learn_cbs,
                splitter=partial(seq2seq_splitter, arch=hf_arch)).to_fp16()

learn.create_opt() 
learn.freeze()

Downloading:   0%|          | 0.00/2.16k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/2.92k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/2.48k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.55k [00:00<?, ?B/s]

In [25]:
# learn.lr_find()

In [26]:
# b = dls.one_batch()
# preds = learn.model(b[0])
# len(preds),preds[0], preds[1].shape

In [27]:
learn.fit_one_cycle(1,
                    lr_max=3e-4,
                    cbs=fit_cbs)

Downloading:   0%|          | 0.00/482 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/878k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/446k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.33G [00:00<?, ?B/s]

In [28]:
learn.show_results(learner=learn, max_n=2)

In [29]:
test_article = """
The past 12 months have been the worst for aviation fatalities so far this decade - with the total of number of people killed if airline 
crashes reaching 1,050 even before the Air Asia plane vanished. Two incidents involving Malaysia Airlines planes - one over eastern Ukraine and the other in the Indian Ocean - led to the deaths of 537 people, while an Air Algerie crash in Mali killed 116 and TransAsia Airways crash in Taiwan killed a further 49 people. The remaining 456 fatalities were largely in incidents involving small commercial planes or private aircraft operating on behalf of companies, governments or organisations. Despite 2014 having the highest number of fatalities so far this decade, the total number of crashes was in fact the lowest since the first commercial jet airliner took off in 1949 - totalling just 111 across the whole world over the past 12 months. The all-time deadliest year for aviation was 1972 when a staggering 2,429 people were killed in a total of 55 plane crashes - including the crash of Aeroflot Flight 217, which killed 174 people in Russia, and Convair 990 Coronado, which claimed 155 lives in Spain. However this year's total death count of 1,212, including those presumed dead on board the missing Air Asia flight, marks a significant rise on the very low 265 fatalities in 2013 - which led to it being named the safest year in aviation since the end of the Second World War. Scroll down for videos. Deadly: The past 12 months have been the worst for aviation fatalities so far this decade - with the total of number of people killed if airline crashes reaching 1,158 even before the Air Asia plane (pictured) vanished. Fatal: Two incidents involving Malaysia Airlines planes - one over eastern Ukraine (pictured) and the other in the Indian Ocean - led to the deaths of 537 people. Surprising: Despite 2014 having the highest number of fatalities so far this decade, the total number of crashes was in fact the lowest since the first commercial jet airliner took off in 1949. 2014 has been a horrific year for Malaysia-based airlines, with 537 people dying on Malaysia Airlines planes, and a further 162 people missing and feared dead in this week's Air Asia incident. In total more than half the people killed in aviation incidents this year had been flying on board Malaysia-registered planes. In January a total of 12 people lost their lives in five separate incidents, while the same number of crashes in February killed 107. 
"""

In [30]:
outputs = learn.blurr_generate(test_article,
                               early_stopping=True,
                               num_beams=4,
                               num_return_sequences=3)

for idx, o in enumerate(outputs):
    print(f'=== Prediction {idx+1} ===\n{o}\n')

=== Prediction 1 ===
The disappearance of Air Asia flight MH17 over eastern Ukraine has led to a dramatic rise in the number of people killed in aviation incidents this year.

=== Prediction 2 ===
The disappearance of Air Asia flight MH17 over eastern Ukraine has led to a dramatic rise in the number of people killed in aviation incidents around the world this year.

=== Prediction 3 ===
The disappearance of Air Asia flight MH17 over eastern Ukraine has led to a dramatic rise in the number of people killed in aviation incidents across the world this year.

In [31]:
df_test = pd.read_csv('news_summary - test.csv', 
                       engine='python',
                       encoding='unicode_escape')

In [32]:
from tqdm import tqdm

for i, row in tqdm(df_test.iterrows()):
  temp = row['Text']
  df_test.at[i, 'pred'] = learn.blurr_generate(temp,
                                               early_stopping=True,
                                               num_beams=1,
                                               num_return_sequences=1)[0]

49it [00:32,  1.49it/s]

In [33]:
from datasets import load_dataset, load_metric

metric = load_metric("rouge")

In [34]:
results = metric.compute(predictions=df_test['pred'],
                         references=df_test['Summary'])
print(results)

{'rouge1': AggregateScore(low=Score(precision=0.3392109226054236, recall=0.11739274163969184, fmeasure=0.1720037378539783), mid=Score(precision=0.4038152914669516, recall=0.14447354504413656, fmeasure=0.20894180418060637), high=Score(precision=0.47036942429291695, recall=0.17430981022805836, fmeasure=0.2494148233077245)), 'rouge2': AggregateScore(low=Score(precision=0.08938900233559703, recall=0.03082881409680332, fmeasure=0.044660740554379304), mid=Score(precision=0.13386999035590785, recall=0.05049813937846094, fmeasure=0.07205134810095126), high=Score(precision=0.18145890787186697, recall=0.07340904089459761, fmeasure=0.10288227768257528)), 'rougeL': AggregateScore(low=Score(precision=0.2588874103754665, recall=0.08656917167338733, fmeasure=0.12772192692076778), mid=Score(precision=0.3118271708184108, recall=0.11052477504961583, fmeasure=0.15995105503028328), high=Score(precision=0.36070135344174514, recall=0.1333609601639444, fmeasure=0.19042411379127838)), 'rougeLsum': AggregateScore(low=Score(precision=0.2603059469504625, recall=0.0866215882709198, fmeasure=0.1277959378373481), mid=Score(precision=0.3119396379543655, recall=0.1104145752821998, fmeasure=0.15963392692535214), high=Score(precision=0.36262638945233194, recall=0.13421992301290336, fmeasure=0.19178423545010548))}

In [35]:
for key in ["rouge1", "rouge2", "rougeL"]:
    print(key, "low:", results[key].low.fmeasure)
    print(key, "mid:", results[key].mid.fmeasure)
    print(key, "high:", results[key].high.fmeasure, end="\n\n")

rouge1 low: 0.1720037378539783
rouge1 mid: 0.20894180418060637
rouge1 high: 0.2494148233077245

rouge2 low: 0.044660740554379304
rouge2 mid: 0.07205134810095126
rouge2 high: 0.10288227768257528

rougeL low: 0.12772192692076778
rougeL mid: 0.15995105503028328
rougeL high: 0.19042411379127838

In [36]:
from nltk.translate.bleu_score import sentence_bleu

In [37]:
df_test.head()

,Summary,Text,pred
0,The Administration of Union Territory Daman and Diu has revoked its order that made it compulsory for women to tie rakhis to their male colleagues on the occasion of Rakshabandhan on August 7. The administration was forced to withdraw the decision within 24 hours of issuing the circular after it received flak from employees and was slammed on social media.,"The Daman and Diu administration on Wednesday withdrew a circular that asked women staff to tie rakhis on male colleagues after the order triggered a backlash from employees and was ripped apart on social media.The union territory?s administration was forced to retreat within 24 hours of issuing the circular that made it compulsory for its staff to celebrate Rakshabandhan at workplace.?It has been decided to celebrate the festival of Rakshabandhan on August 7. In this connection, all offices/ departments shall remain open and celebrate the festival collectively at a suitable time wherein a...",A Hindu festival that is often used as a political tool has become a cause of controversy in a union territory of India.
1,"Malaika Arora slammed an Instagram user who trolled her for ""divorcing a rich man"" and ""having fun with the alimony"". ""Her life now is all about wearing short clothes, going to gym or salon, enjoying vacation[s],"" the user commented. Malaika responded, ""You certainly got to get your damn facts right before spewing sh*t on me...when you know nothing about me.""","From her special numbers to TV?appearances, Bollywood actor Malaika Arora Khan has managed to carve her own identity. The actor, who made her debut in the Hindi film industry with the blockbuster debut opposite Shah Rukh Khan in Chaiyya Chaiyya from Dil Se (1998), is still remembered for the song. However, for trolls, she is a woman first and what matters right now is that she divorced a ?rich man?. On Wednesday, Malaika Arora shared a gorgeous picture of herself on Instagram and a follower decided to troll her for using her ?alumni? (read alimony) money to wear ?short clothes and going t...",Malaika Arora Khan has responded to a troll on Instagram for using her ex-husband's money to buy short clothes and going to gym.
2,"The Indira Gandhi Institute of Medical Sciences (IGIMS) in Patna on Thursday made corrections in its Marital Declaration Form by changing 'Virgin' option to 'Unmarried'. Earlier, Bihar Health Minister defined virgin as being an unmarried woman and did not consider the term objectionable. The institute, however, faced strong backlash for asking new recruits to declare their virginity in the form.","The Indira Gandhi Institute of Medical Sciences (IGIMS) in Patna amended its marital declaration form on Thursday, replacing the word ?virgin? with ?unmarried? after controversy.Until now, new recruits to the super-specialty medical institute in the state capital were required to declare if they were bachelors, widowers or virgins.IGIMS medical superintendent Dr Manish Mandal said institute director Dr NR Biswas held a meeting on Thursday morning before directing that the word ?virgin? on the marital declaration form be immediately replaced with ?unmarried?. Dr Biswas had just returned aft...",A medical institute in Bihar has changed its recruitment form after it was found to be asking new recruits if they were virgins.
3,"Lashkar-e-Taiba's Kashmir commander Abu Dujana, who was killed by security forces, said ""Kabhi hum aage, kabhi aap, aaj aapne pakad liya, mubarak ho aapko (Today you caught me. Congratulations)"" after being caught. He added that he won't surrender, and whatever is in his fate will happen to him. ""Hum nikley they shaheed hone (had left home for martyrdom),"" he added.","Lashkar-e-Taiba's Kashmir commander Abu Dujana was killed in an encounter in a village in Pulwama district of Jammu and Kashmir earlier this week. Dujana, who had managed to give the security forces a slip several times in the past, carried a bounty of Rs 15 lakh on his head.Reports say that Dujana had come to meet his wife when he was trapped inside a house in Hakripora village. Security officials involved in the encounter tried their best to convince Dujana to surrender but he refused, reports say.According to reports, Dujana rejected call for surrender from an Army officer. The Army had...","A top militant killed in an encounter in Indian-administered Kashmir refused to surrender and told security forces that he would do whatever was there in his fate, reports say."
4,"Hotels in Maharashtra will train their staff to spot signs of sex trafficking, including frequent requests for bed linen changes and 'Do not disturb' signs left on room doors for days. A mobile phone app called Rescue Me, which will allow staff to alert police of suspicious behaviour, will be developed. The initiative has been backed by the Maharashtra government.","Hotels in Mumbai and other Indian cities are to train their staff to spot signs of sex trafficking such as frequent requests for bed linen changes or a ""Do not disturb"" sign left on the door for days on end. The group behind the initiative is also developing a mobile phone app - Rescue Me - which hotel staff can use to alert local police and senior anti-trafficking officers if they see suspicious behavior. ""Hotels are breeding grounds for human trade,"" said Sanee Awsarmmel, chairman of the alumni group of Maharashtra State Institute of Hotel Management and Catering Technology. ""(We) have h...","Hotels in India are being trained to spot signs of human trafficking in a bid to help police tackle the problem, a hotel industry group has said."

In [38]:
bleu = []
for i, row in tqdm(df_test.iterrows()):
  bleu.append(sentence_bleu([row['Summary'].split()], row['pred'].split()))

0it [00:00, ?it/s]/usr/local/lib/python3.7/dist-packages/nltk/translate/bleu_score.py:490: UserWarning:
Corpus/Sentence contains 0 counts of 2-gram overlaps.
BLEU scores might be undesirable; use SmoothingFunction().
  warnings.warn(_msg)
49it [00:03, 13.94it/s]

In [39]:
print('bleu   :',   np.mean(bleu))

bleu   : 0.7100570342205084

In [41]:
df_test.to_csv('pegasus.csv', index=False)